language: node_js

node_js:
   - "9"

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli
   - npm install -g node-gyp node-pre-gyp
script: # the build step
   - ng build --configuration=production
